version: '3.8'
services:
  db:
    image: postgres:14.10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
  ganache:
    image: trufflesuite/ganache-cli
    command: -h 0.0.0.0
  web:
    build: ./transcendence
    volumes:
      - ./transcendence:/transcendence
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - REDIRECT_URI=${REDIRECT_URI}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    depends_on:
      - db
      - ganache
    command: sh -c "sleep 5 && cd blockchain && truffle migrate && python /transcendence/manage.py makemigrations && python /transcendence/manage.py migrate && python /transcendence/manage.py runserver 0.0.0.0:8000"
volumes:
  postgres_data: