version: '3.8'
services:
  db:
    image: postgres:14.10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: transcendence_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: "123"
  web:
    build: ./transcendence
    volumes:
      - ./transcendence:/transcendence
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
