# Generated by Django 4.2.9 on 2024-04-09 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_oxomatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
