# Generated by Django 4.2.9 on 2024-04-09 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_match_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxomatch',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oxo_matches_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
