# Generated by Django 4.2.9 on 2024-04-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='final_played',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='final_won',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='semi_played',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='semi_won',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
