# Generated by Django 4.2.9 on 2024-04-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_final_played_user_final_won_user_semi_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
    ]
