# Generated by Django 4.2.9 on 2024-04-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tournamentplayer_tournament_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='player_username',
            field=models.CharField(default='DefaultNickname', max_length=25),
        ),
    ]
