# Generated by Django 4.2.9 on 2024-04-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pong'), (1, 'oxo')], default=0),
        ),
    ]
