# Generated by Django 4.2.9 on 2024-03-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'waiting'), (1, 'accepted'), (2, 'declined'), (3, 'timeout')], default=0),
        ),
    ]
